MODEL:
  TYPE: T2TViT
  NUM_CLASSES: 100
TRANSFORMER:
  PATCH_SIZE: 16
  HIDDEN_DIM: 256
  DEPTH: 7
  NUM_HEADS: 4
  MLP_RATIO: 2
  DROP_RATE: 0.0
  DROP_PATH_RATE: 0.1
  ATTENTION_DROP_RATE: 0.0
T2T:
  TOKEN_DIM: 64
  KERNEL_SIZE: [7, 3, 3]
  STRIDE: [4, 2, 2]
  PADDING: [2, 1, 1]
CNN:
  DEPTH: 56
RESNET:
  TRANS_FUN: basic_transform
DISTILLATION: 
  ENABLE_INTER: False
  INTER_TRANSFORM: linear
  INTER_TEACHER_INDEX: [0, 1, 2]
  INTER_STUDENT_INDEX: [0, 3, 6]
  INTER_WEIGHT: 2.5
  ENABLE_LOGIT: True
  LOGIT_LOSS: "soft"
  LOGIT_TEMP: 1.0
  LOGIT_WEIGHT: 0.5
  TEACHER_MODEL: T2TViT
  TEACHER_IMG_SIZE: 224
  ONLINE: False
  SPACE: True
  SPACE_INTERVAL: 0.5
OPTIM:
  OPTIMIZER: adamw
  BASE_LR: 5.0e-4
  MIN_LR: 5.0e-6
  LR_POLICY: cos
  MAX_EPOCH: 300
  WEIGHT_DECAY: 0.05
  WARMUP_FACTOR: 0.001
  WARMUP_EPOCHS: 20
TRAIN:
  DATASET: cifar100
  SPLIT: train
  BATCH_SIZE: 128
TEST:
  DATASET: cifar100
  SPLIT: test
  BATCH_SIZE: 200
NUM_GPUS: 8
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: False
